package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbCategoriasSubcategorias generated by hbm2java
 */
public class TbCategoriasSubcategorias  implements java.io.Serializable {


     private Integer idCategoriaSubcategoria;
     private TbCategoria tbCategoria;
     private TbSubCategorias tbSubCategorias;
     private Boolean estado;

    public TbCategoriasSubcategorias() {
    }

    public TbCategoriasSubcategorias(TbCategoria tbCategoria, TbSubCategorias tbSubCategorias, Boolean estado) {
       this.tbCategoria = tbCategoria;
       this.tbSubCategorias = tbSubCategorias;
       this.estado = estado;
    }
   
    public Integer getIdCategoriaSubcategoria() {
        return this.idCategoriaSubcategoria;
    }
    
    public void setIdCategoriaSubcategoria(Integer idCategoriaSubcategoria) {
        this.idCategoriaSubcategoria = idCategoriaSubcategoria;
    }
    public TbCategoria getTbCategoria() {
        return this.tbCategoria;
    }
    
    public void setTbCategoria(TbCategoria tbCategoria) {
        this.tbCategoria = tbCategoria;
    }
    public TbSubCategorias getTbSubCategorias() {
        return this.tbSubCategorias;
    }
    
    public void setTbSubCategorias(TbSubCategorias tbSubCategorias) {
        this.tbSubCategorias = tbSubCategorias;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


