package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCajas generated by hbm2java
 */
public class TbCajas  implements java.io.Serializable {


     private Integer idCaja;
     private Boolean estado;
     private Date fecha;
     private Float saldoInicial;
     private Set<TbCorteDeCaja> tbCorteDeCajas = new HashSet<TbCorteDeCaja>(0);
     private Set<TbFacturas> tbFacturases = new HashSet<TbFacturas>(0);
     private Set<TbGastosCajas> tbGastosCajases = new HashSet<TbGastosCajas>(0);

    public TbCajas() {
    }

    public TbCajas(Boolean estado, Date fecha, Float saldoInicial, Set<TbCorteDeCaja> tbCorteDeCajas, Set<TbFacturas> tbFacturases, Set<TbGastosCajas> tbGastosCajases) {
       this.estado = estado;
       this.fecha = fecha;
       this.saldoInicial = saldoInicial;
       this.tbCorteDeCajas = tbCorteDeCajas;
       this.tbFacturases = tbFacturases;
       this.tbGastosCajases = tbGastosCajases;
    }
   
    public Integer getIdCaja() {
        return this.idCaja;
    }
    
    public void setIdCaja(Integer idCaja) {
        this.idCaja = idCaja;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getSaldoInicial() {
        return this.saldoInicial;
    }
    
    public void setSaldoInicial(Float saldoInicial) {
        this.saldoInicial = saldoInicial;
    }
    public Set<TbCorteDeCaja> getTbCorteDeCajas() {
        return this.tbCorteDeCajas;
    }
    
    public void setTbCorteDeCajas(Set<TbCorteDeCaja> tbCorteDeCajas) {
        this.tbCorteDeCajas = tbCorteDeCajas;
    }
    public Set<TbFacturas> getTbFacturases() {
        return this.tbFacturases;
    }
    
    public void setTbFacturases(Set<TbFacturas> tbFacturases) {
        this.tbFacturases = tbFacturases;
    }
    public Set<TbGastosCajas> getTbGastosCajases() {
        return this.tbGastosCajases;
    }
    
    public void setTbGastosCajases(Set<TbGastosCajas> tbGastosCajases) {
        this.tbGastosCajases = tbGastosCajases;
    }




}


