package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbCategoria generated by hbm2java
 */
public class TbCategoria  implements java.io.Serializable {


     private Integer idCategoria;
     private Boolean estado;
     private String nomCategoria;
     private Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases = new HashSet<TbCategoriasSubcategorias>(0);
     private Set<TbCategoriasProducto> tbCategoriasProductos = new HashSet<TbCategoriasProducto>(0);

    public TbCategoria() {
    }

    public TbCategoria(Boolean estado, String nomCategoria, Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases, Set<TbCategoriasProducto> tbCategoriasProductos) {
       this.estado = estado;
       this.nomCategoria = nomCategoria;
       this.tbCategoriasSubcategoriases = tbCategoriasSubcategoriases;
       this.tbCategoriasProductos = tbCategoriasProductos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomCategoria() {
        return this.nomCategoria;
    }
    
    public void setNomCategoria(String nomCategoria) {
        this.nomCategoria = nomCategoria;
    }
    public Set<TbCategoriasSubcategorias> getTbCategoriasSubcategoriases() {
        return this.tbCategoriasSubcategoriases;
    }
    
    public void setTbCategoriasSubcategoriases(Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases) {
        this.tbCategoriasSubcategoriases = tbCategoriasSubcategoriases;
    }
    public Set<TbCategoriasProducto> getTbCategoriasProductos() {
        return this.tbCategoriasProductos;
    }
    
    public void setTbCategoriasProductos(Set<TbCategoriasProducto> tbCategoriasProductos) {
        this.tbCategoriasProductos = tbCategoriasProductos;
    }




}


