package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbCategoriasProducto generated by hbm2java
 */
public class TbCategoriasProducto  implements java.io.Serializable {


     private Integer idCategoriaProducto;
     private TbCategoria tbCategoria;
     private TbProductos tbProductos;
     private Boolean estado;

    public TbCategoriasProducto() {
    }

    public TbCategoriasProducto(TbCategoria tbCategoria, TbProductos tbProductos, Boolean estado) {
       this.tbCategoria = tbCategoria;
       this.tbProductos = tbProductos;
       this.estado = estado;
    }
   
    public Integer getIdCategoriaProducto() {
        return this.idCategoriaProducto;
    }
    
    public void setIdCategoriaProducto(Integer idCategoriaProducto) {
        this.idCategoriaProducto = idCategoriaProducto;
    }
    public TbCategoria getTbCategoria() {
        return this.tbCategoria;
    }
    
    public void setTbCategoria(TbCategoria tbCategoria) {
        this.tbCategoria = tbCategoria;
    }
    public TbProductos getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(TbProductos tbProductos) {
        this.tbProductos = tbProductos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


