package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbClientes generated by hbm2java
 */
public class TbClientes  implements java.io.Serializable {


     private Integer idCliente;
     private TbDirecciones tbDirecciones;
     private TbFacturas tbFacturas;
     private Boolean estado;
     private String dpi;
     private String nombre1;
     private String nombre2;
     private String apellidoP;
     private String apellidoM;
     private String telefono;
     private String email;
     private Date fechaVencimiento;
     private Set<TbFacturas> tbFacturases = new HashSet<TbFacturas>(0);

    public TbClientes() {
    }

    public TbClientes(TbDirecciones tbDirecciones, TbFacturas tbFacturas, Boolean estado, String dpi, String nombre1, String nombre2, String apellidoP, String apellidoM, String telefono, String email, Date fechaVencimiento, Set<TbFacturas> tbFacturases) {
       this.tbDirecciones = tbDirecciones;
       this.tbFacturas = tbFacturas;
       this.estado = estado;
       this.dpi = dpi;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apellidoP = apellidoP;
       this.apellidoM = apellidoM;
       this.telefono = telefono;
       this.email = email;
       this.fechaVencimiento = fechaVencimiento;
       this.tbFacturases = tbFacturases;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public TbDirecciones getTbDirecciones() {
        return this.tbDirecciones;
    }
    
    public void setTbDirecciones(TbDirecciones tbDirecciones) {
        this.tbDirecciones = tbDirecciones;
    }
    public TbFacturas getTbFacturas() {
        return this.tbFacturas;
    }
    
    public void setTbFacturas(TbFacturas tbFacturas) {
        this.tbFacturas = tbFacturas;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Set<TbFacturas> getTbFacturases() {
        return this.tbFacturases;
    }
    
    public void setTbFacturases(Set<TbFacturas> tbFacturases) {
        this.tbFacturases = tbFacturases;
    }




}


