package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbCorteDeCaja generated by hbm2java
 */
public class TbCorteDeCaja  implements java.io.Serializable {


     private Integer idCorteCaja;
     private TbCajas tbCajas;
     private Boolean estado;
     private Float cantidadCierre;

    public TbCorteDeCaja() {
    }

    public TbCorteDeCaja(TbCajas tbCajas, Boolean estado, Float cantidadCierre) {
       this.tbCajas = tbCajas;
       this.estado = estado;
       this.cantidadCierre = cantidadCierre;
    }
   
    public Integer getIdCorteCaja() {
        return this.idCorteCaja;
    }
    
    public void setIdCorteCaja(Integer idCorteCaja) {
        this.idCorteCaja = idCorteCaja;
    }
    public TbCajas getTbCajas() {
        return this.tbCajas;
    }
    
    public void setTbCajas(TbCajas tbCajas) {
        this.tbCajas = tbCajas;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Float getCantidadCierre() {
        return this.cantidadCierre;
    }
    
    public void setCantidadCierre(Float cantidadCierre) {
        this.cantidadCierre = cantidadCierre;
    }




}


