package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCompras generated by hbm2java
 */
public class TbCompras  implements java.io.Serializable {


     private Integer idCompra;
     private Boolean estado;
     private Date fecha;
     private Set<TbDetallesCompras> tbDetallesComprases = new HashSet<TbDetallesCompras>(0);

    public TbCompras() {
    }

    public TbCompras(Boolean estado, Date fecha, Set<TbDetallesCompras> tbDetallesComprases) {
       this.estado = estado;
       this.fecha = fecha;
       this.tbDetallesComprases = tbDetallesComprases;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<TbDetallesCompras> getTbDetallesComprases() {
        return this.tbDetallesComprases;
    }
    
    public void setTbDetallesComprases(Set<TbDetallesCompras> tbDetallesComprases) {
        this.tbDetallesComprases = tbDetallesComprases;
    }




}


