package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbDetallesCompras generated by hbm2java
 */
public class TbDetallesCompras  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private TbCompras tbCompras;
     private TbProductos tbProductos;
     private Boolean estado;
     private Float subtotal;
     private Float total;

    public TbDetallesCompras() {
    }

    public TbDetallesCompras(TbCompras tbCompras, TbProductos tbProductos, Boolean estado, Float subtotal, Float total) {
       this.tbCompras = tbCompras;
       this.tbProductos = tbProductos;
       this.estado = estado;
       this.subtotal = subtotal;
       this.total = total;
    }
   
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public TbCompras getTbCompras() {
        return this.tbCompras;
    }
    
    public void setTbCompras(TbCompras tbCompras) {
        this.tbCompras = tbCompras;
    }
    public TbProductos getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(TbProductos tbProductos) {
        this.tbProductos = tbProductos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


