package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbDetallesFacturas generated by hbm2java
 */
public class TbDetallesFacturas  implements java.io.Serializable {


     private Integer idDetalleFactura;
     private TbFacturas tbFacturas;
     private TbProductos tbProductos;
     private Boolean estado;
     private Integer cantidadDettalleFactura;
     private Float subtotal;
     private Float total;

    public TbDetallesFacturas() {
    }

    public TbDetallesFacturas(TbFacturas tbFacturas, TbProductos tbProductos, Boolean estado, Integer cantidadDettalleFactura, Float subtotal, Float total) {
       this.tbFacturas = tbFacturas;
       this.tbProductos = tbProductos;
       this.estado = estado;
       this.cantidadDettalleFactura = cantidadDettalleFactura;
       this.subtotal = subtotal;
       this.total = total;
    }
   
    public Integer getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(Integer idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }
    public TbFacturas getTbFacturas() {
        return this.tbFacturas;
    }
    
    public void setTbFacturas(TbFacturas tbFacturas) {
        this.tbFacturas = tbFacturas;
    }
    public TbProductos getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(TbProductos tbProductos) {
        this.tbProductos = tbProductos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Integer getCantidadDettalleFactura() {
        return this.cantidadDettalleFactura;
    }
    
    public void setCantidadDettalleFactura(Integer cantidadDettalleFactura) {
        this.cantidadDettalleFactura = cantidadDettalleFactura;
    }
    public Float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Float subtotal) {
        this.subtotal = subtotal;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


