package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbDepartamentos generated by hbm2java
 */
public class TbDepartamentos  implements java.io.Serializable {


     private Integer idDpto;
     private Boolean estado;
     private String nomDpto;
     private Set<TbDirecciones> tbDireccioneses = new HashSet<TbDirecciones>(0);
     private Set<TbMunicipio> tbMunicipios = new HashSet<TbMunicipio>(0);

    public TbDepartamentos() {
    }

    public TbDepartamentos(Boolean estado, String nomDpto, Set<TbDirecciones> tbDireccioneses, Set<TbMunicipio> tbMunicipios) {
       this.estado = estado;
       this.nomDpto = nomDpto;
       this.tbDireccioneses = tbDireccioneses;
       this.tbMunicipios = tbMunicipios;
    }
   
    public Integer getIdDpto() {
        return this.idDpto;
    }
    
    public void setIdDpto(Integer idDpto) {
        this.idDpto = idDpto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomDpto() {
        return this.nomDpto;
    }
    
    public void setNomDpto(String nomDpto) {
        this.nomDpto = nomDpto;
    }
    public Set<TbDirecciones> getTbDireccioneses() {
        return this.tbDireccioneses;
    }
    
    public void setTbDireccioneses(Set<TbDirecciones> tbDireccioneses) {
        this.tbDireccioneses = tbDireccioneses;
    }
    public Set<TbMunicipio> getTbMunicipios() {
        return this.tbMunicipios;
    }
    
    public void setTbMunicipios(Set<TbMunicipio> tbMunicipios) {
        this.tbMunicipios = tbMunicipios;
    }




}


