package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbDirecciones generated by hbm2java
 */
public class TbDirecciones  implements java.io.Serializable {


     private Integer idDireccion;
     private TbDepartamentos tbDepartamentos;
     private TbMunicipio tbMunicipio;
     private Boolean estado;
     private String zona;
     private String calle;
     private Set<TbClientes> tbClienteses = new HashSet<TbClientes>(0);

    public TbDirecciones() {
    }

    public TbDirecciones(TbDepartamentos tbDepartamentos, TbMunicipio tbMunicipio, Boolean estado, String zona, String calle, Set<TbClientes> tbClienteses) {
       this.tbDepartamentos = tbDepartamentos;
       this.tbMunicipio = tbMunicipio;
       this.estado = estado;
       this.zona = zona;
       this.calle = calle;
       this.tbClienteses = tbClienteses;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public TbDepartamentos getTbDepartamentos() {
        return this.tbDepartamentos;
    }
    
    public void setTbDepartamentos(TbDepartamentos tbDepartamentos) {
        this.tbDepartamentos = tbDepartamentos;
    }
    public TbMunicipio getTbMunicipio() {
        return this.tbMunicipio;
    }
    
    public void setTbMunicipio(TbMunicipio tbMunicipio) {
        this.tbMunicipio = tbMunicipio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Set<TbClientes> getTbClienteses() {
        return this.tbClienteses;
    }
    
    public void setTbClienteses(Set<TbClientes> tbClienteses) {
        this.tbClienteses = tbClienteses;
    }




}


