package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbEmpleados generated by hbm2java
 */
public class TbEmpleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private Boolean estado;
     private String nombre1;
     private String nombre2;
     private String apellidoM;
     private String apellidoP;
     private String usuario;
     private String password;
     private Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses = new HashSet<TbFuncionesEmpleados>(0);
     private Set<TbGastosEmpleados> tbGastosEmpleadoses = new HashSet<TbGastosEmpleados>(0);

    public TbEmpleados() {
    }

    public TbEmpleados(Boolean estado, String nombre1, String nombre2, String apellidoM, String apellidoP, String usuario, String password, Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses, Set<TbGastosEmpleados> tbGastosEmpleadoses) {
       this.estado = estado;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apellidoM = apellidoM;
       this.apellidoP = apellidoP;
       this.usuario = usuario;
       this.password = password;
       this.tbFuncionesEmpleadoses = tbFuncionesEmpleadoses;
       this.tbGastosEmpleadoses = tbGastosEmpleadoses;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    public String getApellidoM() {
        return this.apellidoM;
    }
    
    public void setApellidoM(String apellidoM) {
        this.apellidoM = apellidoM;
    }
    public String getApellidoP() {
        return this.apellidoP;
    }
    
    public void setApellidoP(String apellidoP) {
        this.apellidoP = apellidoP;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<TbFuncionesEmpleados> getTbFuncionesEmpleadoses() {
        return this.tbFuncionesEmpleadoses;
    }
    
    public void setTbFuncionesEmpleadoses(Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses) {
        this.tbFuncionesEmpleadoses = tbFuncionesEmpleadoses;
    }
    public Set<TbGastosEmpleados> getTbGastosEmpleadoses() {
        return this.tbGastosEmpleadoses;
    }
    
    public void setTbGastosEmpleadoses(Set<TbGastosEmpleados> tbGastosEmpleadoses) {
        this.tbGastosEmpleadoses = tbGastosEmpleadoses;
    }




}


