package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbFacturas generated by hbm2java
 */
public class TbFacturas  implements java.io.Serializable {


     private Integer idFactura;
     private TbCajas tbCajas;
     private TbClientes tbClientes;
     private Boolean estado;
     private Date fecha;
     private Set<TbDetallesFacturas> tbDetallesFacturases = new HashSet<TbDetallesFacturas>(0);
     private Set<TbClientes> tbClienteses = new HashSet<TbClientes>(0);
     private Set<TbPagos> tbPagoses = new HashSet<TbPagos>(0);

    public TbFacturas() {
    }

    public TbFacturas(TbCajas tbCajas, TbClientes tbClientes, Boolean estado, Date fecha, Set<TbDetallesFacturas> tbDetallesFacturases, Set<TbClientes> tbClienteses, Set<TbPagos> tbPagoses) {
       this.tbCajas = tbCajas;
       this.tbClientes = tbClientes;
       this.estado = estado;
       this.fecha = fecha;
       this.tbDetallesFacturases = tbDetallesFacturases;
       this.tbClienteses = tbClienteses;
       this.tbPagoses = tbPagoses;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public TbCajas getTbCajas() {
        return this.tbCajas;
    }
    
    public void setTbCajas(TbCajas tbCajas) {
        this.tbCajas = tbCajas;
    }
    public TbClientes getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(TbClientes tbClientes) {
        this.tbClientes = tbClientes;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<TbDetallesFacturas> getTbDetallesFacturases() {
        return this.tbDetallesFacturases;
    }
    
    public void setTbDetallesFacturases(Set<TbDetallesFacturas> tbDetallesFacturases) {
        this.tbDetallesFacturases = tbDetallesFacturases;
    }
    public Set<TbClientes> getTbClienteses() {
        return this.tbClienteses;
    }
    
    public void setTbClienteses(Set<TbClientes> tbClienteses) {
        this.tbClienteses = tbClienteses;
    }
    public Set<TbPagos> getTbPagoses() {
        return this.tbPagoses;
    }
    
    public void setTbPagoses(Set<TbPagos> tbPagoses) {
        this.tbPagoses = tbPagoses;
    }




}


