package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbFunciones generated by hbm2java
 */
public class TbFunciones  implements java.io.Serializable {


     private Integer idFuncion;
     private Boolean estado;
     private String nomFuncion;
     private Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses = new HashSet<TbFuncionesEmpleados>(0);

    public TbFunciones() {
    }

    public TbFunciones(Boolean estado, String nomFuncion, Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses) {
       this.estado = estado;
       this.nomFuncion = nomFuncion;
       this.tbFuncionesEmpleadoses = tbFuncionesEmpleadoses;
    }
   
    public Integer getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(Integer idFuncion) {
        this.idFuncion = idFuncion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomFuncion() {
        return this.nomFuncion;
    }
    
    public void setNomFuncion(String nomFuncion) {
        this.nomFuncion = nomFuncion;
    }
    public Set<TbFuncionesEmpleados> getTbFuncionesEmpleadoses() {
        return this.tbFuncionesEmpleadoses;
    }
    
    public void setTbFuncionesEmpleadoses(Set<TbFuncionesEmpleados> tbFuncionesEmpleadoses) {
        this.tbFuncionesEmpleadoses = tbFuncionesEmpleadoses;
    }




}


