package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbFuncionesEmpleados generated by hbm2java
 */
public class TbFuncionesEmpleados  implements java.io.Serializable {


     private Integer idFuncionEmpleado;
     private TbEmpleados tbEmpleados;
     private TbFunciones tbFunciones;
     private Boolean estado;

    public TbFuncionesEmpleados() {
    }

    public TbFuncionesEmpleados(TbEmpleados tbEmpleados, TbFunciones tbFunciones, Boolean estado) {
       this.tbEmpleados = tbEmpleados;
       this.tbFunciones = tbFunciones;
       this.estado = estado;
    }
   
    public Integer getIdFuncionEmpleado() {
        return this.idFuncionEmpleado;
    }
    
    public void setIdFuncionEmpleado(Integer idFuncionEmpleado) {
        this.idFuncionEmpleado = idFuncionEmpleado;
    }
    public TbEmpleados getTbEmpleados() {
        return this.tbEmpleados;
    }
    
    public void setTbEmpleados(TbEmpleados tbEmpleados) {
        this.tbEmpleados = tbEmpleados;
    }
    public TbFunciones getTbFunciones() {
        return this.tbFunciones;
    }
    
    public void setTbFunciones(TbFunciones tbFunciones) {
        this.tbFunciones = tbFunciones;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


