package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbGastos generated by hbm2java
 */
public class TbGastos  implements java.io.Serializable {


     private Integer idGasto;
     private Boolean estado;
     private String nomGasto;
     private Set<TbGastosEmpleados> tbGastosEmpleadoses = new HashSet<TbGastosEmpleados>(0);
     private Set<TbGastosCajas> tbGastosCajases = new HashSet<TbGastosCajas>(0);

    public TbGastos() {
    }

    public TbGastos(Boolean estado, String nomGasto, Set<TbGastosEmpleados> tbGastosEmpleadoses, Set<TbGastosCajas> tbGastosCajases) {
       this.estado = estado;
       this.nomGasto = nomGasto;
       this.tbGastosEmpleadoses = tbGastosEmpleadoses;
       this.tbGastosCajases = tbGastosCajases;
    }
   
    public Integer getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(Integer idGasto) {
        this.idGasto = idGasto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomGasto() {
        return this.nomGasto;
    }
    
    public void setNomGasto(String nomGasto) {
        this.nomGasto = nomGasto;
    }
    public Set<TbGastosEmpleados> getTbGastosEmpleadoses() {
        return this.tbGastosEmpleadoses;
    }
    
    public void setTbGastosEmpleadoses(Set<TbGastosEmpleados> tbGastosEmpleadoses) {
        this.tbGastosEmpleadoses = tbGastosEmpleadoses;
    }
    public Set<TbGastosCajas> getTbGastosCajases() {
        return this.tbGastosCajases;
    }
    
    public void setTbGastosCajases(Set<TbGastosCajas> tbGastosCajases) {
        this.tbGastosCajases = tbGastosCajases;
    }




}


