package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbGastosCajas generated by hbm2java
 */
public class TbGastosCajas  implements java.io.Serializable {


     private Integer idGastosCaja;
     private TbCajas tbCajas;
     private TbGastos tbGastos;
     private Boolean estado;

    public TbGastosCajas() {
    }

    public TbGastosCajas(TbCajas tbCajas, TbGastos tbGastos, Boolean estado) {
       this.tbCajas = tbCajas;
       this.tbGastos = tbGastos;
       this.estado = estado;
    }
   
    public Integer getIdGastosCaja() {
        return this.idGastosCaja;
    }
    
    public void setIdGastosCaja(Integer idGastosCaja) {
        this.idGastosCaja = idGastosCaja;
    }
    public TbCajas getTbCajas() {
        return this.tbCajas;
    }
    
    public void setTbCajas(TbCajas tbCajas) {
        this.tbCajas = tbCajas;
    }
    public TbGastos getTbGastos() {
        return this.tbGastos;
    }
    
    public void setTbGastos(TbGastos tbGastos) {
        this.tbGastos = tbGastos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


