package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbGastosEmpleados generated by hbm2java
 */
public class TbGastosEmpleados  implements java.io.Serializable {


     private Integer idGastosEmpleados;
     private TbEmpleados tbEmpleados;
     private TbGastos tbGastos;
     private Boolean estado;
     private Date fechaHoraGasto;

    public TbGastosEmpleados() {
    }

    public TbGastosEmpleados(TbEmpleados tbEmpleados, TbGastos tbGastos, Boolean estado, Date fechaHoraGasto) {
       this.tbEmpleados = tbEmpleados;
       this.tbGastos = tbGastos;
       this.estado = estado;
       this.fechaHoraGasto = fechaHoraGasto;
    }
   
    public Integer getIdGastosEmpleados() {
        return this.idGastosEmpleados;
    }
    
    public void setIdGastosEmpleados(Integer idGastosEmpleados) {
        this.idGastosEmpleados = idGastosEmpleados;
    }
    public TbEmpleados getTbEmpleados() {
        return this.tbEmpleados;
    }
    
    public void setTbEmpleados(TbEmpleados tbEmpleados) {
        this.tbEmpleados = tbEmpleados;
    }
    public TbGastos getTbGastos() {
        return this.tbGastos;
    }
    
    public void setTbGastos(TbGastos tbGastos) {
        this.tbGastos = tbGastos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaHoraGasto() {
        return this.fechaHoraGasto;
    }
    
    public void setFechaHoraGasto(Date fechaHoraGasto) {
        this.fechaHoraGasto = fechaHoraGasto;
    }




}


