package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbMarcas generated by hbm2java
 */
public class TbMarcas  implements java.io.Serializable {


     private Integer idMarca;
     private Boolean estado;
     private String nomMarca;
     private Set<TbProductos> tbProductoses = new HashSet<TbProductos>(0);

    public TbMarcas() {
    }

    public TbMarcas(Boolean estado, String nomMarca, Set<TbProductos> tbProductoses) {
       this.estado = estado;
       this.nomMarca = nomMarca;
       this.tbProductoses = tbProductoses;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomMarca() {
        return this.nomMarca;
    }
    
    public void setNomMarca(String nomMarca) {
        this.nomMarca = nomMarca;
    }
    public Set<TbProductos> getTbProductoses() {
        return this.tbProductoses;
    }
    
    public void setTbProductoses(Set<TbProductos> tbProductoses) {
        this.tbProductoses = tbProductoses;
    }




}


