package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbMunicipio generated by hbm2java
 */
public class TbMunicipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private TbDepartamentos tbDepartamentos;
     private Boolean estado;
     private String nomMunicipio;
     private Integer codigoPostal;
     private Set<TbDirecciones> tbDireccioneses = new HashSet<TbDirecciones>(0);

    public TbMunicipio() {
    }

    public TbMunicipio(TbDepartamentos tbDepartamentos, Boolean estado, String nomMunicipio, Integer codigoPostal, Set<TbDirecciones> tbDireccioneses) {
       this.tbDepartamentos = tbDepartamentos;
       this.estado = estado;
       this.nomMunicipio = nomMunicipio;
       this.codigoPostal = codigoPostal;
       this.tbDireccioneses = tbDireccioneses;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public TbDepartamentos getTbDepartamentos() {
        return this.tbDepartamentos;
    }
    
    public void setTbDepartamentos(TbDepartamentos tbDepartamentos) {
        this.tbDepartamentos = tbDepartamentos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomMunicipio() {
        return this.nomMunicipio;
    }
    
    public void setNomMunicipio(String nomMunicipio) {
        this.nomMunicipio = nomMunicipio;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Set<TbDirecciones> getTbDireccioneses() {
        return this.tbDireccioneses;
    }
    
    public void setTbDireccioneses(Set<TbDirecciones> tbDireccioneses) {
        this.tbDireccioneses = tbDireccioneses;
    }




}


