package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbPagos generated by hbm2java
 */
public class TbPagos  implements java.io.Serializable {


     private Integer idPago;
     private TbFacturas tbFacturas;
     private TbTiposPagos tbTiposPagos;
     private Boolean estado;

    public TbPagos() {
    }

    public TbPagos(TbFacturas tbFacturas, TbTiposPagos tbTiposPagos, Boolean estado) {
       this.tbFacturas = tbFacturas;
       this.tbTiposPagos = tbTiposPagos;
       this.estado = estado;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public TbFacturas getTbFacturas() {
        return this.tbFacturas;
    }
    
    public void setTbFacturas(TbFacturas tbFacturas) {
        this.tbFacturas = tbFacturas;
    }
    public TbTiposPagos getTbTiposPagos() {
        return this.tbTiposPagos;
    }
    
    public void setTbTiposPagos(TbTiposPagos tbTiposPagos) {
        this.tbTiposPagos = tbTiposPagos;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


