package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbProductos generated by hbm2java
 */
public class TbProductos  implements java.io.Serializable {


     private Integer idProducto;
     private TbMarcas tbMarcas;
     private Boolean estado;
     private String nombreProducto;
     private Date fechaCaducidad;
     private Integer stock;
     private Set<TbDetallesFacturas> tbDetallesFacturases = new HashSet<TbDetallesFacturas>(0);
     private Set<TbCategoriasProducto> tbCategoriasProductos = new HashSet<TbCategoriasProducto>(0);
     private Set<TbProductoProveedor> tbProductoProveedors = new HashSet<TbProductoProveedor>(0);
     private Set<TbDetallesCompras> tbDetallesComprases = new HashSet<TbDetallesCompras>(0);

    public TbProductos() {
    }

    public TbProductos(TbMarcas tbMarcas, Boolean estado, String nombreProducto, Date fechaCaducidad, Integer stock, Set<TbDetallesFacturas> tbDetallesFacturases, Set<TbCategoriasProducto> tbCategoriasProductos, Set<TbProductoProveedor> tbProductoProveedors, Set<TbDetallesCompras> tbDetallesComprases) {
       this.tbMarcas = tbMarcas;
       this.estado = estado;
       this.nombreProducto = nombreProducto;
       this.fechaCaducidad = fechaCaducidad;
       this.stock = stock;
       this.tbDetallesFacturases = tbDetallesFacturases;
       this.tbCategoriasProductos = tbCategoriasProductos;
       this.tbProductoProveedors = tbProductoProveedors;
       this.tbDetallesComprases = tbDetallesComprases;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public TbMarcas getTbMarcas() {
        return this.tbMarcas;
    }
    
    public void setTbMarcas(TbMarcas tbMarcas) {
        this.tbMarcas = tbMarcas;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Set<TbDetallesFacturas> getTbDetallesFacturases() {
        return this.tbDetallesFacturases;
    }
    
    public void setTbDetallesFacturases(Set<TbDetallesFacturas> tbDetallesFacturases) {
        this.tbDetallesFacturases = tbDetallesFacturases;
    }
    public Set<TbCategoriasProducto> getTbCategoriasProductos() {
        return this.tbCategoriasProductos;
    }
    
    public void setTbCategoriasProductos(Set<TbCategoriasProducto> tbCategoriasProductos) {
        this.tbCategoriasProductos = tbCategoriasProductos;
    }
    public Set<TbProductoProveedor> getTbProductoProveedors() {
        return this.tbProductoProveedors;
    }
    
    public void setTbProductoProveedors(Set<TbProductoProveedor> tbProductoProveedors) {
        this.tbProductoProveedors = tbProductoProveedors;
    }
    public Set<TbDetallesCompras> getTbDetallesComprases() {
        return this.tbDetallesComprases;
    }
    
    public void setTbDetallesComprases(Set<TbDetallesCompras> tbDetallesComprases) {
        this.tbDetallesComprases = tbDetallesComprases;
    }




}


