package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbProveedores generated by hbm2java
 */
public class TbProveedores  implements java.io.Serializable {


     private Integer idProveedor;
     private Boolean estado;
     private String nombreProveedor;
     private Set<TbProductoProveedor> tbProductoProveedors = new HashSet<TbProductoProveedor>(0);

    public TbProveedores() {
    }

    public TbProveedores(Boolean estado, String nombreProveedor, Set<TbProductoProveedor> tbProductoProveedors) {
       this.estado = estado;
       this.nombreProveedor = nombreProveedor;
       this.tbProductoProveedors = tbProductoProveedors;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public Set<TbProductoProveedor> getTbProductoProveedors() {
        return this.tbProductoProveedors;
    }
    
    public void setTbProductoProveedors(Set<TbProductoProveedor> tbProductoProveedors) {
        this.tbProductoProveedors = tbProductoProveedors;
    }




}


