package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1



/**
 * TbProductoProveedor generated by hbm2java
 */
public class TbProductoProveedor  implements java.io.Serializable {


     private Integer idProductoProveedor;
     private TbProductos tbProductos;
     private TbProveedores tbProveedores;
     private Boolean estado;

    public TbProductoProveedor() {
    }

    public TbProductoProveedor(TbProductos tbProductos, TbProveedores tbProveedores, Boolean estado) {
       this.tbProductos = tbProductos;
       this.tbProveedores = tbProveedores;
       this.estado = estado;
    }
   
    public Integer getIdProductoProveedor() {
        return this.idProductoProveedor;
    }
    
    public void setIdProductoProveedor(Integer idProductoProveedor) {
        this.idProductoProveedor = idProductoProveedor;
    }
    public TbProductos getTbProductos() {
        return this.tbProductos;
    }
    
    public void setTbProductos(TbProductos tbProductos) {
        this.tbProductos = tbProductos;
    }
    public TbProveedores getTbProveedores() {
        return this.tbProveedores;
    }
    
    public void setTbProveedores(TbProveedores tbProveedores) {
        this.tbProveedores = tbProveedores;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


