package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbSubCategorias generated by hbm2java
 */
public class TbSubCategorias  implements java.io.Serializable {


     private Integer idSubCategorias;
     private Boolean estado;
     private String nomSubCategorias;
     private Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases = new HashSet<TbCategoriasSubcategorias>(0);

    public TbSubCategorias() {
    }

    public TbSubCategorias(Boolean estado, String nomSubCategorias, Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases) {
       this.estado = estado;
       this.nomSubCategorias = nomSubCategorias;
       this.tbCategoriasSubcategoriases = tbCategoriasSubcategoriases;
    }
   
    public Integer getIdSubCategorias() {
        return this.idSubCategorias;
    }
    
    public void setIdSubCategorias(Integer idSubCategorias) {
        this.idSubCategorias = idSubCategorias;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNomSubCategorias() {
        return this.nomSubCategorias;
    }
    
    public void setNomSubCategorias(String nomSubCategorias) {
        this.nomSubCategorias = nomSubCategorias;
    }
    public Set<TbCategoriasSubcategorias> getTbCategoriasSubcategoriases() {
        return this.tbCategoriasSubcategoriases;
    }
    
    public void setTbCategoriasSubcategoriases(Set<TbCategoriasSubcategorias> tbCategoriasSubcategoriases) {
        this.tbCategoriasSubcategoriases = tbCategoriasSubcategoriases;
    }




}


