package Pojos;
// Generated 16-oct-2020 16:13:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbTiposPagos generated by hbm2java
 */
public class TbTiposPagos  implements java.io.Serializable {


     private Integer idTipoPago;
     private Boolean estado;
     private String nombreTipoPago;
     private Float recargo;
     private Set<TbPagos> tbPagoses = new HashSet<TbPagos>(0);

    public TbTiposPagos() {
    }

    public TbTiposPagos(Boolean estado, String nombreTipoPago, Float recargo, Set<TbPagos> tbPagoses) {
       this.estado = estado;
       this.nombreTipoPago = nombreTipoPago;
       this.recargo = recargo;
       this.tbPagoses = tbPagoses;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNombreTipoPago() {
        return this.nombreTipoPago;
    }
    
    public void setNombreTipoPago(String nombreTipoPago) {
        this.nombreTipoPago = nombreTipoPago;
    }
    public Float getRecargo() {
        return this.recargo;
    }
    
    public void setRecargo(Float recargo) {
        this.recargo = recargo;
    }
    public Set<TbPagos> getTbPagoses() {
        return this.tbPagoses;
    }
    
    public void setTbPagoses(Set<TbPagos> tbPagoses) {
        this.tbPagoses = tbPagoses;
    }




}


